package com.aeert.droolsdemo.fact;
global com.aeert.droolsdemo.service.CheckService checkService;

dialect  "mvel"

rule "fugitive"
    salience 2
    no-loop
    when
        $person : Person(checkService.isFugitive($person))
    then
        System.out.println("这个人是逃犯，先稳住，再报警！");
end

rule "age"
    salience 1
    no-loop
    when
        $person : Person(age<16 || age>50)
    then
        System.out.println("这个人的年龄不符合要求, 不允许上机。");
end

